// This file contains all the data for your portfolio.
// Update this file to change your skills, projects, and links without touching the UI code.

export const siteData = {
  personal: {
    name: "Oskar Pajka",
    role: "Full-Stack Developer",
    bio: "A Full-Stack Developer passionate about building clean, fast, and accessible web applications. I love experimenting with new frameworks.",
    availability: "Available for work",
    email: process.env.NEXT_PUBLIC_CONTACT_EMAIL || "hello@oskarpajka.me",
  },
  socials: {
    github: "https://github.com/oskarpajka",
    linkedin: "#",
  },
  skills: [
    "Swift",
    "SwiftUI",
    "Xcode",
    "Next.js",
    "React",
    "TypeScript",
    "Node.js",
    "Tailwind CSS",
    "PostgreSQL",
    "Python",
    "C++",
    "Git",
  ],
  bentoProjects: [
    {
      id: "portfolio",
      title: "Portfolio Website",
      description: "A neo-brutalist personal portfolio built with Next.js App Router and Tailwind CSS.",
      tech: ["Next.js", "Tailwind", "TypeScript"],
      link: "https://github.com/oskarpajka/portfolio",
      color: "bg-white",
      iconBg: "bg-red-500",
      iconColor: "text-white",
    },
    {
      id: "cera",
      title: "Cera",
      description: "Context-aware iOS translation app improving accuracy by leveraging surrounding context.",
      tech: ["SwiftUI", "Xcode", "iOS"],
      link: "https://github.com/oskarpajka/Cera",
      color: "bg-orange-500",
      iconBg: "bg-black",
      iconColor: "text-white",
      textColor: "text-white",
    },
  ],
  featuredWorks: [
    {
      id: "project-alpha",
      title: "Project Alpha",
      category: "Web Application",
      year: "2026",
      link: "#",
      color: "hover:bg-yellow-400",
      shortDescription: "A placeholder description for a future web application project.",
      longDescription: "This is a detailed placeholder description for Project Alpha. Once completed, this section will detail the problem solved, the architecture designed, and the impact of the application. It features a modern tech stack and scalable infrastructure.",
      techStack: ["React", "Node.js", "PostgreSQL"],
    },
    {
      id: "project-beta",
      title: "Project Beta",
      category: "SaaS Platform",
      year: "2025",
      link: "#",
      color: "hover:bg-purple-500",
      shortDescription: "A placeholder description for a future SaaS platform.",
      longDescription: "This is a detailed placeholder description for Project Beta. Once completed, this section will detail the problem solved, the architecture designed, and the impact of the application. It features a modern tech stack and scalable infrastructure.",
      techStack: ["Next.js", "Tailwind", "Stripe"],
    },
    {
      id: "project-gamma",
      title: "Project Gamma",
      category: "Mobile App",
      year: "2025",
      link: "#",
      color: "hover:bg-red-500",
      shortDescription: "A placeholder description for a future mobile application.",
      longDescription: "This is a detailed placeholder description for Project Gamma. Once completed, this section will detail the problem solved, the architecture designed, and the impact of the application. It features a modern tech stack and scalable infrastructure.",
      techStack: ["SwiftUI", "CoreData", "iOS"],
    },
    {
      id: "project-delta",
      title: "Project Delta",
      category: "Tooling",
      year: "2024",
      link: "#",
      color: "hover:bg-orange-500",
      shortDescription: "A placeholder description for a future developer tool.",
      longDescription: "This is a detailed placeholder description for Project Delta. Once completed, this section will detail the problem solved, the architecture designed, and the impact of the application. It features a modern tech stack and scalable infrastructure.",
      techStack: ["TypeScript", "CLI", "Node.js"],
    },
  ],
};
